site_name: Hashgraph Online
site_url: hashgraphonline.com
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.footer
    - navigation.sections
    - navigation.tabs
copyright: Copyright &copy; 2024 Hashgraph Online
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/HashgraphOnline
plugins:
  - social
  - search
  - mkdocs-nav-weight